### ISSUE TITLE
[Request]: Load network config from file

### ISSUE THREAD

**Issue by shufps** [iotaledger/evm-toolkit#17]
### Feature description

Load network config file dynamically instead of compile it statically into the package.

### Motivation

Currently the network config is statically compiled into the package what makes building docker images more complicated because we need a docker image with the correct config inside the docker for each network.

It would be great if the network config could be loaded dynamically at start.

This way we can use a common built docker image (by Github CI) and just mount the correct network config file into the container

Here is a PR that already did this (and it worked, before it was removed during migration of the evm-toolkit from the wasp to the evm-toolkit repository).

https://github.com/iotaledger/wasp/pull/1914

### Requirements

1. Someone re-integrating the PR

### Are you planning to do it yourself in a pull request?

No

**Comment by shufps** [comment]
It seems, the current version is a looot different than the evm-toolkit for which the PR was.

The PR dynamically loaded the json when opening the app. 

I wonder if the json file couldn't be just loaded when starting the docker (and therefore the app) once instead of requesting the file each time when someone opens the app in the browser.

But idk how Svelte works - but it also would be fine, if a file just could be loaded at docker container start.

**Comment by shufps** [comment]
new PR: https://github.com/iotaledger/evm-toolkit/pull/18

**Comment by begonaalvarezd** [comment]
Closed by https://github.com/iotaledger/evm-toolkit/pull/18
